name: LegadoGoogleB

on: 
  watch:
    types: [started]
env:
  #  Your legado git url
  git_url: 'https://github.com/gedoor/legado.git'
  #  Your legado git tag
  git_tag: 
  # Your legado custom script
  app_custom: 'diy_10bits.sh'
  # Legado app name
  app_name: '阅读Pro+'
  # Legado app suffix
  app_suffix: 'B'
  # Legado app launch name
  app_launch_name: '阅读Pro+'
  # Legado app rename enable
  app_rename: 'true'


jobs:
  build_apk:
    if: github.repository_owner == github.actor
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        
    - name: set env
      shell: bash
      env:
        SECRETS_APP_NAME: ${{ env.app_name }}
        SECRETS_GIT_URL: ${{ env.git_url }}
        SECRETS_SUFFIX: ${{ env.app_suffix }}
        SECRETS_ENABLE: ${{ secrets.ENABLE }}
        SECRETS_MINIFY: ${{ secrets.MINIFY }}
        SECRETS_RENAME: ${{ env.app_rename }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_ACTOR: ${{ github.actor }}
        SECRETS_TAG: ${{ env.git_tag }}
        SECRETS_LAUNCH_NAME: ${{ env.app_launch_name }}
      run: source $GITHUB_WORKSPACE/google_action_setenv.sh
    
    - name: clone code
      shell: bash
      run: source $GITHUB_WORKSPACE/action_clone.sh

    - name: custom your app
      shell: bash
      env:
        custom: ${{ env.app_custom }}
      run: |
        source $GITHUB_WORKSPACE/action_app_custom.sh
        
    - name: build  your app
      if: success()
      shell: bash
      run: |
        source $GITHUB_WORKSPACE/google_action_build.sh
        app_build

#    - name: upload artifact
#      uses: actions/upload-artifact@v2
#      if: success()
#      with:
#        name: ${{ env.APP_UPLOAD_NAME }}
#        path: ${{ env.APP_UPLOAD }}

    - name: Upload ProPlus To Lanzou
      env:
        # 登录蓝奏云后在控制台运行document.cookie
        ylogin: ${{ secrets.ylogin }}
        phpdisk_info: ${{ secrets.phpdisk_info }}
        # 蓝奏云里的文件夹ID
        LANZOU_FOLDER_ID: ${{ secrets.LANZOU_FOLDER_ID }}
        path: "/opt/legado/app/build/outputs/apk/google/release/"
        typeName: "阅读ProPlus_共存"
      if: ${{ env.ylogin }}
      run: |
        rm -rf /opt/legado/app/build/outputs/apk/google/release/*.json
        sudo mv /opt/legado/app/build/outputs/apk/google/release/*.apk /opt/legado/app/build/outputs/apk/google/release/$typeName"_"$APP_TAG.apk
        python3 $GITHUB_WORKSPACE/.github/scripts/lzy_web.py "$path" "$LANZOU_FOLDER_ID"
        echo "[$(date -u -d '+8 hour' '+%Y.%m.%d %H:%M:%S')]"
        cd /opt/legado/app/build/outputs/
        pwd
        tree

#    - name: upload to webdav
#      if: success()
#      shell: bash
#      env:
#        WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
#        WEBDAV_AUTH: ${{ secrets.WEBDAV_AUTH }}
#        WEBDAV_UPLOAD: ${{ secrets.WEBDAV_UPLOAD }}
#      run: |
#        source $GITHUB_WORKSPACE/action_util.sh
#        webdav_upload $APP_UPLOAD/*.apk
        
